version: "3"
services:
  pibloom-api:
    image: pibloom-api
    container_name: pibloom-api
    restart: unless-stopped
    build:
      context: ./piBLOOM_api
    environment:
      - N_WORKERS=2 # number of uvicorn workers for unicorn api server
    ports:
      - 5000:5000
    networks:
      - pinet

  pibloom-web:
    image: pibloom-web
    container_name: pibloom-web
    restart: unless-stopped
    build:
      context: ./piBLOOM_web
    ports:
      - 8080:8080
    networks:
      - pinet
  
  # pibloom-proxy:
  #   image: pibloom-proxy
  #   container_name: pibloom-proxy
  #   restart: unless-stopped
  #   build:
  #     context: ./piBLOOM_proxy
  #   ports:
  #     - 80:80
  #   networks:
  #     - pinet

networks:
  pinet:
    driver: bridge