services:
  pibloom_api:
    build:
      context: ./piBLOOM_api
    environment:
      - N_WORKERS=2 # number of uvicorn workers for unicorn api server
    ports:
      - 5000:5000
    networks:
      - pinet

  pibloom_web:
    build:
      context: ./piBLOOM_web
    ports:
      - 8080:8080
    networks:
      - pinet
  
  pibloom_proxy:
    build:
      context: ./piBLOOM_proxy
    ports:
      - 80:80
    networks:
      - pinet

networks:
  pinet:
    driver: bridge