services:
  pibloom_api:
    build:
      context: ./piBLOOM_api
    environment:
      - N_WORKERS=2 # number of uvicorn workers for unicorn api server
    ports:
      - 5000:5000

  pibloom_web:
    build: ./piBLOOM_web
    ports:
      - 8080:8080